### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by miso-belica** [Joozty/Base-user-management-system#1]
Hi @Joozty we checked BUMS and there are some serious bugs:

1. Please remove and add to `.gitignore` IDEA config files (folder `.idea`). I want to have my own settings for project. With your settings IDEA windows is hidden somewhere for me :(
2. You commited SQLLite DB into git. This is also not good. We want to have own DB with users. You should remove it and add into gitignore too.
3. Creation of users does not work because of missing parameter `db`. Did you test it?
4. And also deletion is not working because link on Frontend has wrong URL.
5. Deletion of users does not work even after I fixed the link because you are trying to get email from [wrong parameter](https://github.com/Joozty/Base-user-management-system/blob/master/form.py#L51). Did you test it?

Can you please fix these problems and let us know?

**Comment by Joozty** [comment]
1. Done
2. Done
3. Are you sure? I tested it and everything works fine. DB parameters was missing only in docstring. 
4. Sorry my mistake.

**Comment by martinvy** [comment]
@Joozty Parameter `db` is missing on [lline 86](https://github.com/Joozty/Base-user-management-system/blob/master/main.py#L86) and on [line 62](https://github.com/Joozty/Base-user-management-system/blob/master/main.py#L62) in `main.py`.

**Comment by Joozty** [comment]
@martinvy Thank you. Fixed

**Comment by miso-belica** [comment]
Thanks
